[auth]
redirect_uri = "http://localhost:8501/oauth2callback"
cookie_secret = "ffH6MuRe5RcJ21r7"
client_id = "322bb6e6-6262-468c-a33c-9bb2834d70ac"
client_secret = "Yzp8Q~dDvWzHAr3aB_ZqdR5rjcvD.jL~0TwjZdvY"
server_metadata_url = "https://login.microsoftonline.com/09b0ae42-9b0d-4104-8bd1-30e650dcfabf/v2.0/.well-known/openid-configuration"