[auth]
redirect_uri = "http://localhost:8501/oauth2callback"
cookie_secret = "ffH6MuRe5RcJ21r7"
client_id = "789ef9c1-0dae-4374-9155-3147fd0074ee"
client_secret = "I~G8Q~Zmk8Dg079t0yOa~3O6YkkdhhafbU2dKbFh"
server_metadata_url = "https://login.microsoftonline.com/consumers/v2.0/.well-known/openid-configuration"